### PR TITLE
AdvancedPlayable.StartAsync

### PR DESCRIPTION
**Pull request by romanoza**
I've added a new method 'AdvancedPlayable.StartAsync()', which allows me to use this code in the asynchronous manner.

### CODE REVIEW

**Comment by MathewSachin** [comment]
I have a question on it.
If we want to manually stop playback, what would be the approach on the Task object

**Comment by MathewSachin** [comment]
It would be better if you follow the code formatting style followed throughout the project

**Comment by MathewSachin** [comment]
Start() returns bool.
You will have to mark the task as failed when Start() returns false providing details in exception with Bass.LastError

**Comment by MathewSachin** [comment]
If user calls Stop(), will that be reported in the Task

**Comment by romanoza** [comment]
I see. Never mind, this modification is causing other problems I see now. I'll withdraw this pull request.

**Comment by MathewSachin** [comment]
Ok. But I appreciate your willingness to contribute

**Pull request closed without merging**
